tap "anomalyco/tap"
tap "blacktop/tap"
tap "iina/mpv-iina"
tap "koekeishiya/formulae"
tap "lihaoyun6/tap"
tap "lencx/chatgpt", "https://github.com/lencx/ChatGPT.git"
tap "steipete/tap"

brew "bash"
brew "bash-completion@2"
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "grep"
brew "mas"
brew "openssh"
brew "screen"
brew "wget"
brew "curl"
