brew "dockutil"
brew "koekeishiya/formulae/skhd"

cask "alt-tab"
cask "dockdoor"
cask "espanso"
cask "glance-chamburr"
cask "hammerspoon"
cask "hiddenbar"
cask "jordanbaird-ice"
cask "jurplel/tap/instant-space-switcher"
cask "karabiner-elements"
cask "lihaoyun6/tap/quickrecorder"
cask "logi-options+"
cask "qlmarkdown"
cask "rectangle"
cask "scroll-reverser"
cask "stats"
